version: '3.1'    

networks:
  fr-net:

services:

  gunicorn:
    restart: always
    networks:
      - fr-net
    expose:
      - "8000"
    links:
      - postgres
    volumes:
      - ../back:/back
    env_file:
      - .env
    build: ../back
    command: "/usr/local/bin/gunicorn -w 2 --env SCRIPT_NAME=/api_v1 -b :8000 --chdir back app:app"

  nginx:
    image: nginx:1.16  
    networks:
      - fr-net     
    restart: always
    volumes:
      - ../front/build:/front # Front-End React Project
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${WEB_PORT}:80
      #- 443:443
    links:
      - gunicorn

  postgres:
    image: postgres:12.2    
    environment:
      POSTGRES_DB: "fr_auth_db"
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - fr-net
    restart: on-failure
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql 
      # Next Line for specific data location 
      #- ./db/postgres-data:/var/lib/postgresql/data
